# CNS3XXX Platform Support
snd-soc-cns3xxx-objs := cns3xxx-pcm.o
snd-soc-cns3xxx-i2s-objs := cns3xxx-i2s.o

obj-$(CONFIG_SND_CNS3XXX_SOC) += snd-soc-cns3xxx.o
obj-$(CONFIG_SND_CNS3XXX_SOC_I2S) += snd-soc-cns3xxx-i2s.o

# CNS3XXX Machine Support
snd-soc-chip-objs := cns3xxx.o

obj-$(CONFIG_SND_CNS3XXX_SOC_CHIP) += snd-soc-chip.o

snd-soc-pcm1-objs := cns3xxx-pcm1dac.o
snd-soc-pcm1-fmt-objs := cns3xxx-pcm1dac-fmt.o
snd-soc-pcm1-trnsfr-objs := cns3xxx-pcm1dac-pcm.o

obj-$(CONFIG_SND_CNS3XXX_SOC_PCM1) += snd-soc-pcm1.o
obj-$(CONFIG_SND_CNS3XXX_SOC_PCM1_FMT) += snd-soc-pcm1-fmt.o
obj-$(CONFIG_SND_CNS3XXX_SOC_PCM1_TRNSFR) += snd-soc-pcm1-trnsfr.o
